[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environment]
NODE_ENV = "production"
PORT = "3000"

[http]
path = "/"
port = "3000"

[[services]]
name = "my-ci-cd-app"
type = "web"